dist: precise
language: 
  - cpp
compiler: 
  - gcc
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq freeglut3-dev
  - sudo apt-get install -qq libsoil-dev
  - sudo apt-get install -qq libglm-dev
script: 
  # - make
  # - ./bin/terror-project
branches:
  only:
    - master
